version: "3.9"

services:
  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      - MEILI_MASTER_KEY=masterKey
    volumes:
      - "ms_data:/data.ms"
    ports:
      - "7700:7700"

volumes:
  ms_data:
